server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: category-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/genres/**

        - id: element-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/books/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
